### ISSUE TITLE
pip install 这个插件时下载的了，最后无法安装

### ISSUE THREAD

**Issue by 715494637** [chrisyy2003/nonebot-plugin-gpt3#1]
![Uploading bandicam 2022-12-21 17-46-22-553.jpg…]()
用pip安装插件时下载完成但是无法安装
pip install 这个插件时下载的了，最后没有安装
其次我在隔壁的大佬那里白嫖到了免费API的方法，奈何自己毫无语言基础
求大佬能增加一个免费API的功能   
下面是大佬写出的东西
[免KEY接口分析.docx](https://github.com/chrisyy2003/nonebot-plugin-gpt3/files/10276730/KEY.docx)

**Comment by chrisyy2003** [comment]
这个图看不到，pip install装的话，需要在bot.py里面手动添加一下

**Comment by 715494637** [comment]
PS C:\Users\QWQ\source\repos\gtp3> pip install nonebot_plugin_gpt3
Collecting nonebot_plugin_gpt3
  Using cached nonebot_plugin_gpt3-1.0.9-py3-none-any.whl (6.8 kB)
Requirement already satisfied: nonebot-adapter-onebot<3.0.0,>=2.1.5 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from nonebot_plugin_gpt3) (2.2.0)
Requirement already satisfied: nonebot-plugin-htmlrender<0.3.0.0,>=0.2.0.1 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from nonebot_plugin_gpt3) (0.2.0.1)
Requirement already satisfied: nonebot2<3.0.0,>=2.0.0rc2 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from nonebot_plugin_gpt3) (2.0.0rc2)
Collecting openai<0.26.0,>=0.25.0
  Using cached openai-0.25.0-py3-none-any.whl
Requirement already satisfied: pyyaml<7.0,>=6.0 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from nonebot_plugin_gpt3) (6.0)
Collecting transformers<5.0.0,>=4.25.1
  Using cached transformers-4.25.1-py3-none-any.whl (5.8 MB)
Requirement already satisfied: msgpack<2.0.0,>=1.0.3 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from nonebot-adapter-onebot<3.0.0,>=2.1.5->nonebot_plugin_gpt3) (1.0.4)
Requirement already satisfied: Pygments<3.0.0,>=2.10.0 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from nonebot-plugin-htmlrender<0.3.0.0,>=0.2.0.1->nonebot_plugin_gpt3) (2.13.0)
Requirement already satisfied: aiofiles<0.9.0,>=0.8.0 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from nonebot-plugin-htmlrender<0.3.0.0,>=0.2.0.1->nonebot_plugin_gpt3) (0.8.0)
Requirement already satisfied: jinja2<4.0.0,>=3.0.3 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from nonebot-plugin-htmlrender<0.3.0.0,>=0.2.0.1->nonebot_plugin_gpt3) (3.1.2)
Requirement already satisfied: markdown<4.0.0,>=3.3.6 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from nonebot-plugin-htmlrender<0.3.0.0,>=0.2.0.1->nonebot_plugin_gpt3) (3.4.1)
Requirement already satisfied: playwright<2.0.0,>=1.17.2 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from nonebot-plugin-htmlrender<0.3.0.0,>=0.2.0.1->nonebot_plugin_gpt3) (1.28.0)
Requirement already satisfied: pymdown-extensions<10.0,>=9.1 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from nonebot-plugin-htmlrender<0.3.0.0,>=0.2.0.1->nonebot_plugin_gpt3) (9.9)
Requirement already satisfied: python-markdown-math<0.9,>=0.8 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from nonebot-plugin-htmlrender<0.3.0.0,>=0.2.0.1->nonebot_plugin_gpt3) (0.8)
Requirement already satisfied: fastapi<1.0.0,>=0.87.0 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from nonebot2<3.0.0,>=2.0.0rc2->nonebot_plugin_gpt3) (0.88.0)
Requirement already satisfied: loguru<0.7.0,>=0.6.0 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from nonebot2<3.0.0,>=2.0.0rc2->nonebot_plugin_gpt3) (0.6.0)
Requirement already satisfied: pydantic[dotenv]<2.0.0,>=1.10.0 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from nonebot2<3.0.0,>=2.0.0rc2->nonebot_plugin_gpt3) (1.10.2)
Requirement already satisfied: pygtrie<3.0.0,>=2.4.1 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from nonebot2<3.0.0,>=2.0.0rc2->nonebot_plugin_gpt3) (2.5.0)
Requirement already satisfied: tomlkit<1.0.0,>=0.10.0 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from nonebot2<3.0.0,>=2.0.0rc2->nonebot_plugin_gpt3) (0.11.6)
Requirement already satisfied: typing-extensions<5.0.0,>=3.10.0 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from nonebot2<3.0.0,>=2.0.0rc2->nonebot_plugin_gpt3) (4.4.0)
Requirement already satisfied: uvicorn[standard]<1.0.0,>=0.20.0 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from nonebot2<3.0.0,>=2.0.0rc2->nonebot_plugin_gpt3) (0.20.0)
Requirement already satisfied: yarl<2.0.0,>=1.7.2 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from nonebot2<3.0.0,>=2.0.0rc2->nonebot_plugin_gpt3) (1.8.2)
Requirement already satisfied: requests>=2.20 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from openai<0.26.0,>=0.25.0->nonebot_plugin_gpt3) (2.28.1)
Collecting tqdm
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting pandas>=1.2.3
  Using cached pandas-1.5.2-cp311-cp311-win_amd64.whl (10.3 MB)
Collecting pandas-stubs>=1.1.0.11
  Using cached pandas_stubs-1.5.2.221213-py3-none-any.whl (147 kB)
Collecting openpyxl>=3.0.7
  Using cached openpyxl-3.0.10-py2.py3-none-any.whl (242 kB)
Collecting numpy
  Using cached numpy-1.24.0-cp311-cp311-win_amd64.whl (14.8 MB)
Collecting filelock
  Using cached filelock-3.8.2-py3-none-any.whl (10 kB)
Collecting huggingface-hub<1.0,>=0.10.0
  Using cached huggingface_hub-0.11.1-py3-none-any.whl (182 kB)
Collecting packaging>=20.0
  Using cached packaging-22.0-py3-none-any.whl (42 kB)
Collecting regex!=2019.12.17
  Using cached regex-2022.10.31-cp311-cp311-win_amd64.whl (267 kB)
Collecting tokenizers!=0.11.3,<0.14,>=0.11.1
  Using cached tokenizers-0.13.2.tar.gz (359 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: starlette==0.22.0 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from fastapi<1.0.0,>=0.87.0->nonebot2<3.0.0,>=2.0.0rc2->nonebot_plugin_gpt3) (0.22.0)
Requirement already satisfied: anyio<5,>=3.4.0 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from starlette==0.22.0->fastapi<1.0.0,>=0.87.0->nonebot2<3.0.0,>=2.0.0rc2->nonebot_plugin_gpt3) (3.6.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from jinja2<4.0.0,>=3.0.3->nonebot-plugin-htmlrender<0.3.0.0,>=0.2.0.1->nonebot_plugin_gpt3) (2.1.1)
Requirement already satisfied: colorama>=0.3.4 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from loguru<0.7.0,>=0.6.0->nonebot2<3.0.0,>=2.0.0rc2->nonebot_plugin_gpt3) (0.4.6)
Requirement already satisfied: win32-setctime>=1.0.0 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from loguru<0.7.0,>=0.6.0->nonebot2<3.0.0,>=2.0.0rc2->nonebot_plugin_gpt3) (1.1.0)
Collecting et-xmlfile
  Using cached et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.2.3->openai<0.26.0,>=0.25.0->nonebot_plugin_gpt3) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.2.3->openai<0.26.0,>=0.25.0->nonebot_plugin_gpt3) (2022.7)
Collecting types-pytz>=2022.1.1
  Using cached types_pytz-2022.7.0.0-py3-none-any.whl (4.7 kB)
Requirement already satisfied: greenlet==2.0.1 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from playwright<2.0.0,>=1.17.2->nonebot-plugin-htmlrender<0.3.0.0,>=0.2.0.1->nonebot_plugin_gpt3) (2.0.1)
Requirement already satisfied: pyee==9.0.4 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from playwright<2.0.0,>=1.17.2->nonebot-plugin-htmlrender<0.3.0.0,>=0.2.0.1->nonebot_plugin_gpt3) (9.0.4)
Requirement already satisfied: python-dotenv>=0.10.4 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from pydantic[dotenv]<2.0.0,>=1.10.0->nonebot2<3.0.0,>=2.0.0rc2->nonebot_plugin_gpt3) (0.21.0)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.20->openai<0.26.0,>=0.25.0->nonebot_plugin_gpt3) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.20->openai<0.26.0,>=0.25.0->nonebot_plugin_gpt3) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.20->openai<0.26.0,>=0.25.0->nonebot_plugin_gpt3) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.20->openai<0.26.0,>=0.25.0->nonebot_plugin_gpt3) (2022.12.7)
Requirement already satisfied: click>=7.0 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from uvicorn[standard]<1.0.0,>=0.20.0->nonebot2<3.0.0,>=2.0.0rc2->nonebot_plugin_gpt3) (8.1.3)
Requirement already satisfied: h11>=0.8 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from uvicorn[standard]<1.0.0,>=0.20.0->nonebot2<3.0.0,>=2.0.0rc2->nonebot_plugin_gpt3) (0.14.0)
Requirement already satisfied: httptools>=0.5.0 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from uvicorn[standard]<1.0.0,>=0.20.0->nonebot2<3.0.0,>=2.0.0rc2->nonebot_plugin_gpt3) (0.5.0)
Requirement already satisfied: watchfiles>=0.13 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from uvicorn[standard]<1.0.0,>=0.20.0->nonebot2<3.0.0,>=2.0.0rc2->nonebot_plugin_gpt3) (0.18.1)
Requirement already satisfied: websockets>=10.4 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from uvicorn[standard]<1.0.0,>=0.20.0->nonebot2<3.0.0,>=2.0.0rc2->nonebot_plugin_gpt3) (10.4)
Requirement already satisfied: multidict>=4.0 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from yarl<2.0.0,>=1.7.2->nonebot2<3.0.0,>=2.0.0rc2->nonebot_plugin_gpt3) (6.0.3)
Requirement already satisfied: six>=1.5 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.1->pandas>=1.2.3->openai<0.26.0,>=0.25.0->nonebot_plugin_gpt3) (1.16.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\qwq\appdata\local\programs\python\python311\lib\site-packages (from anyio<5,>=3.4.0->starlette==0.22.0->fastapi<1.0.0,>=0.87.0->nonebot2<3.0.0,>=2.0.0rc2->nonebot_plugin_gpt3) (1.3.0)
Building wheels for collected packages: tokenizers
  Building wheel for tokenizers (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for tokenizers (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\tokenizers
      copying py_src\tokenizers\__init__.py -> build\lib.win-amd64-cpython-311\tokenizers
      creating build\lib.win-amd64-cpython-311\tokenizers\models
      copying py_src\tokenizers\models\__init__.py -> build\lib.win-amd64-cpython-311\tokenizers\models
      creating build\lib.win-amd64-cpython-311\tokenizers\decoders
      copying py_src\tokenizers\decoders\__init__.py -> build\lib.win-amd64-cpython-311\tokenizers\decoders
      creating build\lib.win-amd64-cpython-311\tokenizers\normalizers
      copying py_src\tokenizers\normalizers\__init__.py -> build\lib.win-amd64-cpython-311\tokenizers\normalizers
      creating build\lib.win-amd64-cpython-311\tokenizers\pre_tokenizers
      copying py_src\tokenizers\pre_tokenizers\__init__.py -> build\lib.win-amd64-cpython-311\tokenizers\pre_tokenizers
      creating build\lib.win-amd64-cpython-311\tokenizers\processors
      copying py_src\tokenizers\processors\__init__.py -> build\lib.win-amd64-cpython-311\tokenizers\processors
      creating build\lib.win-amd64-cpython-311\tokenizers\trainers
      copying py_src\tokenizers\trainers\__init__.py -> build\lib.win-amd64-cpython-311\tokenizers\trainers
      creating build\lib.win-amd64-cpython-311\tokenizers\implementations
      copying py_src\tokenizers\implementations\base_tokenizer.py -> build\lib.win-amd64-cpython-311\tokenizers\implementations
      copying py_src\tokenizers\implementations\bert_wordpiece.py -> build\lib.win-amd64-cpython-311\tokenizers\implementations
      copying py_src\tokenizers\implementations\byte_level_bpe.py -> build\lib.win-amd64-cpython-311\tokenizers\implementations
      copying py_src\tokenizers\implementations\char_level_bpe.py -> build\lib.win-amd64-cpython-311\tokenizers\implementations
      copying py_src\tokenizers\implementations\sentencepiece_bpe.py -> build\lib.win-amd64-cpython-311\tokenizers\implementations
      copying py_src\tokenizers\implementations\sentencepiece_unigram.py -> build\lib.win-amd64-cpython-311\tokenizers\implementations
      copying py_src\tokenizers\implementations\__init__.py -> build\lib.win-amd64-cpython-311\tokenizers\implementations
      creating build\lib.win-amd64-cpython-311\tokenizers\tools
      copying py_src\tokenizers\tools\visualizer.py -> build\lib.win-amd64-cpython-311\tokenizers\tools
      copying py_src\tokenizers\tools\__init__.py -> build\lib.win-amd64-cpython-311\tokenizers\tools
      copying py_src\tokenizers\__init__.pyi -> build\lib.win-amd64-cpython-311\tokenizers
      copying py_src\tokenizers\models\__init__.pyi -> build\lib.win-amd64-cpython-311\tokenizers\models
      copying py_src\tokenizers\decoders\__init__.pyi -> build\lib.win-amd64-cpython-311\tokenizers\decoders
      copying py_src\tokenizers\normalizers\__init__.pyi -> build\lib.win-amd64-cpython-311\tokenizers\normalizers
      copying py_src\tokenizers\pre_tokenizers\__init__.pyi -> build\lib.win-amd64-cpython-311\tokenizers\pre_tokenizers
      copying py_src\tokenizers\processors\__init__.pyi -> build\lib.win-amd64-cpython-311\tokenizers\processors
      copying py_src\tokenizers\trainers\__init__.pyi -> build\lib.win-amd64-cpython-311\tokenizers\trainers
      copying py_src\tokenizers\tools\visualizer-styles.css -> build\lib.win-amd64-cpython-311\tokenizers\tools
      running build_ext
      running build_rust
      error: can't find Rust compiler

      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

      To update pip, run:

          pip install --upgrade pip

      and then retry package installation.

      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tokenizers
Failed to build tokenizers
ERROR: Could not build wheels for tokenizers, which is required to install pyproject.toml-based projects
PS C:\Users\QWQ\source\repos\gtp3>

**Comment by chrisyy2003** [comment]
windows用户还需要安装一个rust环境，[点击这里下载安装](https://file.chrisyy.top/rustup-setup.exe)

**Comment by chrisyy2003** [comment]
那个免api的我发现他网页已经用不了了

**Comment by pk4ever1** [comment]
用nb安装也会报错
nb plugin install nonebot-plugin-gpt3

需要改下配置文件
pyproject.toml
里面
"nonebot-plugin-gpt3"改成"nonebot_plugin_gpt3"能解决

**Comment by pk4ever1** [comment]
还有个问题。自动生成的配置文件和说明文档里的默认文件名不一致

**Comment by chrisyy2003** [comment]
> 还有个问题。自动生成的配置文件和说明文档里的默认文件名不一致

已修复

**Comment by 715494637** [comment]
终于退烧了，一会试试
感谢大佬

**Comment by TomorrowLost** [comment]
不需要科学网？
