### ISSUE TITLE
插件未运行

### ISSUE THREAD

**Issue by kongxiangyi88** [chrisyy2003/nonebot-plugin-gpt3#10]
插件已经加载了，key已经输入了，切换人格的什么都能用，但是那个对话消息就是触发不了，后台好像也显示没有反应
![Uploading Screenshot_20230112_173721
![Screenshot_20230113_100027_mark via](https://user-images.githubusercontent.com/102857431/212219818-871037b5-5408-444a-ae77-2be403ff716d.jpg)
.jpg…]()

**Comment by kongxiangyi88** [comment]
![Uploading Screenshot_20230112_173721.jpg…]()

**Comment by chrisyy2003** [comment]
那应该是触发命令设置的不对吧，设置个特别的试试
比如
`gpt3_command_prefix = "gpt3" `
然后 `gpt3 你好`

**Comment by SaltyF1sh312** [comment]
.env.dev里加上这句话：COMMAND_START=["/", ""]  # 配置命令起始字符

**Comment by kongxiangyi88** [comment]
改了，但是不知道为什么还是没有触发，后台也是没反应，插件已经运行了，这里我改成别的了，后来我又改成你说的了，但是还是没反应
![Uploading Screenshot_20230113_202441_mark.via_edit_12895537435531.jpg…]()

**Comment by kongxiangyi88** [comment]
![Screenshot_20230113_203919_com mapp](https://user-images.githubusercontent.com/102857431/212322379-1798c375-4a89-4c2a-8190-17ae545150f8.jpg)
这里是info，有影响吗？

**Comment by SaltyF1sh312** [comment]
你的Current Env是prod，应该在.env.prod里修改配置，加上那句话

**Comment by kongxiangyi88** [comment]
还是不行，话说这个要代理吗？而且设置人格不是超管也可以设置。我闲下来重新获取一下key重试下，麻烦您了。

**Comment by chrisyy2003** [comment]
每个人会话不一样，设置是自己的会话



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月13日(周五) 晚上9:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chrisyy2003/nonebot-plugin-gpt3] 插件未运行 (Issue #10)




 
还是不行，话说这个要代理吗？而且设置人格不是超管也可以设置。我闲下来重新获取一下key重试下，麻烦您了。

**Comment by kongxiangyi88** [comment]
![Screenshot_20230116_215805_com mapp_edit_130684997925354](https://user-images.githubusercontent.com/102857431/212695843-690efa5e-072b-4455-a0c1-828837e8f284.jpg)
是不是apikey哪没写好，胡搞了一个，下有反应了，但回复发生错误: Incorrect API key provided: ]. You can find your API key at https://beta.openai.com.

**Comment by SaltyF1sh312** [comment]
检查一下你环境文件中的`gpt3_api_key_path`是否设置正确。因为这条报错的意思是你提供的不正确的API key为`]`，与你截图中的API key并不符合，说明用到的key并不在截图的文件中。

**Comment by kongxiangyi88** [comment]
抱歉没接触过这个，照网上教程部署的bot，可以问一下这个gpt3_api_key_path在什么位置吗？麻烦您了。

**Comment by chrisyy2003** [comment]
openai最近，即使是对的api key好像也会出问题，确保填对了后可以稍后再试
