### ISSUE TITLE
请问如何切换成群体对话？群内成员共用同一会话

### ISSUE THREAD

**Issue by Kiana1314** [chrisyy2003/nonebot-plugin-gpt3#12]
rt

**Comment by chrisyy2003** [comment]
描述一下功能可以吗，同一时间群是一个会话
还是
开启一个会话，然后群员需要主动加入到某个会话中？

**Comment by Kiana1314** [comment]
听起来都挺不错的，开启后让群员都处在同一会话，或者是创立一个会话让别人选择加入

**Comment by chrisyy2003** [comment]
似乎不是一样的，第一种可能需要管理员才能开启一个公用对话，第二种每个人都可以

**Comment by Kiana1314** [comment]
比如这个，能切换就行了佬
用配置项或者指令都可
![image](https://user-images.githubusercontent.com/107671434/213409833-2ac9a3b3-32f2-4a73-a119-eb8897af6c5e.png)

**Comment by chrisyy2003** [comment]
https://github.com/chrisyy2003/nonebot-plugin-gpt3/commit/6acd12d8a7344bf1a1efd856b2f84eb644b8841e 
已经加入了这个功能

**Comment by Kiana1314** [comment]
谢谢佬
