### ISSUE TITLE
使用插件出现错误

### ISSUE THREAD

**Issue by linkedlist771** [chrisyy2003/nonebot-plugin-gpt3#13]
使用插件时出现以下报错：
“You requested a model that is not compatible with this engine.”
与[https://community.openai.com/t/error-you-requested-a-model-that-is-not-compatible-with-this-engine-when-using-codex-in-playground/35153/1](url) 存在相同的问题。

**Comment by chrisyy2003** [comment]
这不是插件的问题，用的openai的官方库
