### ISSUE TITLE
建议一个新功能

### ISSUE THREAD

**Issue by YYY-919** [chrisyy2003/nonebot-plugin-gpt3#14]
设置人格、重置会话等操作需要为管理员

**Comment by YYY-919** [comment]
如果可以的话，拜托再增添一个开关在配置中

**Comment by chrisyy2003** [comment]
设置人格已经改为需要管理员设置了，`pip install nonebot-plugin-gpt3 -U`
重置会话没必要管理员吧，每个人是单独的会话

**Comment by YYY-919** [comment]
> 设置人格已经改为需要管理员设置了，`pip install nonebot-plugin-gpt3 -U`
> 
> 重置会话没必要管理员吧，每个人是单独的会话

谢谢大大
