### ISSUE TITLE
为什么我的gpt3说今年是2020年

### ISSUE THREAD

**Issue by GOT-youze** [chrisyy2003/nonebot-plugin-gpt3#18]
为什么我的gpt3说今年是2020年，是OpenAI开放的是2020年的库吗

**Comment by YYY-919** [comment]
OpenAI的问题，你可以告诉它今年是2023年，~~但它有时候会反驳~~

**Comment by RokasUrbelis** [comment]
实际调用的是GPT2？

[这里的](https://github.com/chrisyy2003/nonebot-plugin-gpt3/blob/main/nonebot_plugin_gpt3/__init__.py) 第8行：
tokenizer = GPT2TokenizerFast.from_pretrained("gpt2")

**Comment by chrisyy2003** [comment]
Gpt3好像是2020年
chatgpt是2021
