### ISSUE TITLE
机器人回复问题

### ISSUE THREAD

**Issue by KotoriKoi** [chrisyy2003/nonebot-plugin-gpt3#19]
![Screenshot_2023-02-11-02-00-34-352_com tencent mo](https://user-images.githubusercontent.com/91445888/218163540-a73861a2-c1df-469e-89bb-af833122490d.jpg)

按照主页的截图测试的，不知道是不是只有我存在这个问题

**Comment by chrisyy2003** [comment]
> ![image](https://user-images.githubusercontent.com/51810656/218456304-4cfcc76a-61a3-439f-88a7-b9167701d557.png) 图片渲染代码不能格式化一下？

这个是回复的内容，插件不是很好格式化

**Comment by chrisyy2003** [comment]
[6473edf](https://github.com/chrisyy2003/nonebot-plugin-gpt3/commit/6473edf51d26b6135a80ebcc4a4ae2ebcf1b75db) fix
