### ISSUE TITLE
没有反应，什么报错都没有

### ISSUE THREAD

**Issue by JiliHili** [chrisyy2003/nonebot-plugin-gpt3#2]
![APIK](https://user-images.githubusercontent.com/102945328/209443826-1821fe5d-0fa7-4635-91b6-434b6f1f11c5.png)
![APIKR](https://user-images.githubusercontent.com/102945328/209443830-6469a443-bd27-4d9e-9dad-f5ab73739d78.png)

**Comment by JiliHili** [comment]
![CT](https://user-images.githubusercontent.com/102945328/209443870-055dc14e-1d83-4a5a-a177-ed58ebd1f76a.png)

**Comment by chrisyy2003** [comment]
nonebot默认命令前面有个斜杠，在env.dev里面配置command star

**Comment by JiliHili** [comment]
> nonebot默认命令前面有个斜杠，在env.dev里面配置command star

把我自己的插件移出去就好了，没找到是什么问题..感谢回复

**Comment by chrisyy2003** [comment]
可能冲突了，检查下日志
