### ISSUE TITLE
可以支持一下nb2b5版本吗

### ISSUE THREAD

**Issue by NanakoOfficial** [chrisyy2003/nonebot-plugin-gpt3#22]
一升rc版本插件都炸完了:(

**Comment by chrisyy2003** [comment]
这个可以直接clone一下项目到自己的qqbot目录，然后改一下nonebot2的版本，再安装一下依赖就可以了

**Comment by NanakoOfficial** [comment]
> 这个可以直接clone一下项目到自己的qqbot目录，然后改一下nonebot2的版本，再安装一下依赖就可以了

安装依赖后再把nb版本降回去应该可以吧

**Comment by chrisyy2003** [comment]
可以的，反正就不要直接安装这个插件

**Comment by NanakoOfficial** [comment]
谢谢！
