### ISSUE TITLE
其他插件的指令消息被拦截

### ISSUE THREAD

**Issue by Kiana1314** [chrisyy2003/nonebot-plugin-gpt3#26]
![IMG_20230222_173033](https://user-images.githubusercontent.com/107671434/220590121-323d0ee2-32db-4223-a577-39f2f65903a9.jpg)

![Screenshot_2023-02-22-17-31-59-640-edit_com tencent mobileqq](https://user-images.githubusercontent.com/107671434/220590587-4bb5cfac-4349-405e-8103-0e2563640411.jpg)

![Screenshot_2023-02-22-18-13-23-454-edit_com tencent mobileqq](https://user-images.githubusercontent.com/107671434/220590223-1c657bf6-6daa-4a65-bd18-69a85a5c3ba1.jpg)

**Comment by chrisyy2003** [comment]
可以改一下源码中的数字就好了，数字越大匹配优先级越低
不过这里的“不可以”为什么会触发gpt3插件呢
