### ISSUE TITLE
预置人格问题

### ISSUE THREAD

**Issue by Arymodu** [chrisyy2003/nonebot-plugin-gpt3#32]
大佬你好，想问一下能不能关闭预置人格？

**Comment by chrisyy2003** [comment]
请问什么意思

**Comment by Arymodu** [comment]
您的插件预置了AI助手的人格，因此在询问的时候AI会如此自称，并且认为自己是根据ChatGPT开发的AI助手。但有时我想关闭它，所以请问能否关闭预置的人格。

**Comment by chrisyy2003** [comment]
就是没有任何人格的预设吗

**Comment by Arymodu** [comment]
> 就是没有任何人格的预设吗

是的。

**Comment by chrisyy2003** [comment]
[d8d890b](https://github.com/chrisyy2003/nonebot-plugin-gpt3/commit/d8d890b13e55725a8be2fa24e3aa369b110f6141) fix
