### ISSUE TITLE
聊天聊着聊着保这个错误

### ISSUE THREAD

**Issue by smallka1** [chrisyy2003/nonebot-plugin-gpt3#33]
![QQ图片20230304105122](https://user-images.githubusercontent.com/108041850/222872216-acf82f0d-7f35-411d-bd10-fa0cb722a68c.jpg)

**Comment by yufanChan** [comment]
我也这样了，感觉是ip又ban了

**Comment by yufanChan** [comment]
个人已解决，方法：尝试更新openSSL
```shell
pip install pyopenssl
pip install pyopenssl --upgrade
```
如果使用虚拟环境，在虚拟环境更新即可
```shell
venv\Scripts\activate.bat #开启虚拟环境
deactivate #关闭虚拟环境
```

**Comment by chrisyy2003** [comment]
被墙了，在请在终端挂代理

**Comment by webjoin111** [comment]
> 被墙了，请在终端挂代理

奇怪，之前版本是没这问题的，我代理也始终开着，现在一直提示这个，而且我打开API界面没有使用的记录。

**Comment by smallka1** [comment]
算了，挂了代理还是不行。。。

**Comment by smallka1** [comment]
算了，挂了代理还是不行。。。

**Comment by chrisyy2003** [comment]
https://github.com/chrisyy2003/nonebot-plugin-gpt3/issues/31
