### ISSUE TITLE
 能否支持逆向库呢？

### ISSUE THREAD

**Issue by QingMuCat** [chrisyy2003/nonebot-plugin-gpt3#35]
逆向库地址：https://github.com/acheong08/ChatGPT
如果可以，能不能加入accessToken，SessionToken认证登录呢？

**Comment by chrisyy2003** [comment]
用accessToken，SessionToken认证登录应该是登陆chatgpt吧，但是我记得有chatgpt的nonebot插件，利用token登陆的
