### ISSUE TITLE
请求token长度大于模型最大token长度

### ISSUE THREAD

**Issue by SihenZhang** [chrisyy2003/nonebot-plugin-gpt3#36]
* 插件版本：`1.1.3`
* `openai`版本：`0.27.0`
* 模型版本：`gpt-3.5-turbo`

在聊天开始时，会有概率出现请求token长度大于模型最大token长度的情况，如下图所示。

<img src="https://user-images.githubusercontent.com/20498895/222969155-5e510864-64ce-4316-9d76-0346078727cc.png" alt="1678028941763" width="360" />
<img src="https://user-images.githubusercontent.com/20498895/222969202-e5a4c91c-efc3-4424-8932-a9d6acb8bb5a.png" alt="1678028941756" width="360" />

**Comment by chrisyy2003** [comment]
fix,https://github.com/chrisyy2003/nonebot-plugin-gpt3/commit/9abf146f8e5f8f86ffe7073d1b8133a9d0ec8cea
