### ISSUE TITLE
链接超时错误

### ISSUE THREAD

**Issue by 769763549** [chrisyy2003/nonebot-plugin-gpt3#37]
发生错误: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002406F0B8C10>, 'Connection to api.openai.com timed out. (connect timeout=600)'))
![QQ图片20230306152959](https://user-images.githubusercontent.com/98259451/223045934-972a6079-ab46-4d95-8c49-0ae92b45cd1a.png)

**Comment by 769763549** [comment]
请问一下是什么问题

**Comment by chrisyy2003** [comment]
https://github.com/chrisyy2003/nonebot-plugin-gpt3/issues/31

**Comment by 769763549** [comment]
![QQ图片20230306172812](https://user-images.githubusercontent.com/98259451/223070328-5e218a13-d8d8-43ca-a642-5cc2e49b3de0.png)
![53EF266B3C4D7F6BFCDD74306BDAFC96](https://user-images.githubusercontent.com/98259451/223070350-c90472cb-fb16-4f47-9d51-23db120a6ab3.jpg)
大佬，我改完直接没有反应了，不过api是没有问题的啊

**Comment by chrisyy2003** [comment]
你发一下日志呢
