### ISSUE TITLE
Error communicating with OpenAI

### ISSUE THREAD

**Issue by NanakoOfficial** [chrisyy2003/nonebot-plugin-gpt3#38]
发生错误: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000029AA7BEEB20>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

大佬你好，请问一下这个报错是因为API被墙的缘故吗，配置文件里可以支持写代理吗

**Comment by chrisyy2003** [comment]
查看最新的readme进行配置，需要代理
![56818b762242db8cbb7e0fefcbe8b647](https://user-images.githubusercontent.com/63803385/223336246-a960c7da-846b-404a-b0f2-f54ec0dd7b29.png)

**Comment by chrisyy2003** [comment]
https://github.com/chrisyy2003/nonebot-plugin-gpt3/issues/31

**Comment by NanakoOfficial** [comment]
> https://github.com/chrisyy2003/nonebot-plugin-gpt3/issues/31

感谢感谢
