### ISSUE TITLE
想问一下佬为什么配置完sign_gold和security_gold后悔报错

### ISSUE THREAD

**Issue by Arama-Vanarana** [chrisyy2003/nonebot-plugin-gpt3#4]
![uTools_1673243383171](https://user-images.githubusercontent.com/122252361/211247645-21ed2b7b-ee65-4d98-a5f0-c09b7fc4bd2d.png)

**Comment by Arama-Vanarana** [comment]
斯标题打错字了

**Comment by chrisyy2003** [comment]
psign_gold和security_gold是什么

**Comment by Arama-Vanarana** [comment]
那个变量







                       
原始邮件
                       
                     

发件人："chrisyy2003"< ***@***.*** &gt;;

发件时间：2023/1/9 14:31

收件人："chrisyy2003/nonebot-plugin-gpt3"< ***@***.*** &gt;;

抄送人："Arama-Vanarana"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [chrisyy2003/nonebot-plugin-gpt3] 想问一下佬为什么配置完sign_gold和security_gold后悔报错 (Issue #4)




 
psign_gold和security_gold是什么
 
&mdash;

**Comment by Arama-Vanarana** [comment]
擦我按错网页了(悲)
