### ISSUE TITLE
bug:部分qq号消息无法响应

### ISSUE THREAD

**Issue by ElainaFanBoy** [chrisyy2003/nonebot-plugin-gpt3#41]
03-08 16:43:12 [SUCCESS] nonebot | ONEBOT V11 2545044071 | [message.group.normal]: Message 470695935 from 1270217000@[群:925353737] 'gpt 原神是否有抄袭塞尔达'
03-08 16:43:12 [INFO] nonebot | Event message.group.normal is ignored

**Comment by NanakoOfficial** [comment]
比如1270217000这个qq号，看后台gpt3插件根本没有响应，不知道怎么回事其它人都能正常响应0.0

**Comment by chrisyy2003** [comment]
奇怪，日志看能不能多发一点，这个号对其他插件有问题吗还是只是这个插件没响应
