### ISSUE TITLE
服务器过载后对话就重置了

### ISSUE THREAD

**Issue by Kiana1314** [chrisyy2003/nonebot-plugin-gpt3#5]
服务器过载后会话报错：
发生错误: The server is overloaded or not ready yet.
或者：
![V)ZA1IVI@_0}4AR`F55J8`7](https://user-images.githubusercontent.com/107671434/211583696-45ca57c1-4ed1-46c4-971a-6e335cd65025.png)
之后对话就重置了，请问有解决方法吗，比如多设置几个key

**Comment by chrisyy2003** [comment]
配置文件里可以填入多个key

**Comment by Kiana1314** [comment]
多个key会影响每个人的单独会话进程吗

**Comment by chrisyy2003** [comment]
不会

**Comment by Kiana1314** [comment]
好的 谢谢佬
